"""
AI Agent Models - Data classes and models for the AI agent system
"""

from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional


@dataclass
class Message:
    id: str
    content: str
    username: str
    userId: str
    timestamp: str
    room: str
    isAutoGenerated: bool = False


@dataclass
class ConversationContext:
    messages: List[Message]
    room_id: str
    last_ai_response: Optional[datetime] = None
    code_context: str = ""
    programming_language: str = "python"
    problem_description: str = ""
    problem_title: str = ""
    
    # Execution results tracking
    last_execution_code: str = ""
    last_execution_output: str = ""
    last_execution_error: str = ""
    last_execution_success: bool = True
    last_execution_time: Optional[datetime] = None
    
    # Simple timestamp tracking
    last_message_time: Optional[datetime] = None  # When the last message was received
    
    # Planning check tracking - only run once per session
    planning_check_done: bool = False
